/opt/zimbra/bin/zmmailbox -z -m alam.khan@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m zoheb.khan@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m vipul.kanade@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m anis.charania@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m sanjeet.lukked@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m james.kasbe@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m tanmay.khandekar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m mohammed.ajaney@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m mohsin.shaikh@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ajitsingh.bhagwania@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m amarjeet.bhosale@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m anil.mendon@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ashley.barnabas@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m makarand.kumbhar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m elias.naidu@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ravindra.muthukondu@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m jagdish.mulchandani@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m deepak.pundit@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m kevin.francis@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m lawmsangkimi.khiangte@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m shilpa.mehta@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m aniruddha.jagtap@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m daanish.samuel@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m shailesh.parmar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m nabab.sharif@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ritu.rai@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ashish.ojha@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ritesh.waghela@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m suketu.mehta@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m yaseer.ahmad@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m rohit.bhadoriya@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m rohan.manohar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m mariojayson.grimes@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m sandesh.pichake@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m govindswamy.naidu@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m suraj.ghosh@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m satyajeet.mohapatra@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m wasim.shaikh@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m sneha.giri@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m prithvi.tribhuvan@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m rishikesh.surve@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m tabish.shaikh@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m durgesh.balriya@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m dominic.daniel@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m somesh.abellu@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m neel.shah@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m renuka.dasari@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m hemant.pandey@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m vaishali.khairnar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m anirudh.singhbais@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m george.mcardo@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m akanksha.khemka@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m sunny.wadke@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m milind.gaikwad@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m altamash.sayyed@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m glen.dass@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m kevin.augustin@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m shweta.solanki@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m nikhil.yadav@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m alimohammed.kara@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m amreen.meghani@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m amit.gaikwad@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m raees.khan@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m vinod.singh@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m nadir.merchant@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m vishal.rajput@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ruturaj.pande@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m atul.patole@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m nikhil.lognathan@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m lusinle.khing@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m abhishek.sahay@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m alice.chettiar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m abhishek.gautam@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m amrita.barua@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m yogesh.awchite@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ashish.prateek@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m shilpa.kandulna@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m deepti.budhgaonkar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m rohit.naidu@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m yasmin.kherale@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m angad.yadav@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m cassandra.ramsay@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m daljit.sabharwal@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m rohit.mane@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m vinod.antony@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m abhinay.kumar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m farhan.abaji@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m nitin.manik@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m bodke.mangesh@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m shrikant.priyadorshi@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m rupfukhoyi.rhakho@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m shakti.singh@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m somba.chang@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m tariq.changa@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m suraj.malwade@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m nikhil.gotur@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m abhishek.vijaykumar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m tsering.namgyal@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m swati.whatkar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m steffy.gowley@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m yogesh.nimgaonkar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m sapnesh.wadker@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m vineet.lakhanpal@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m nikita.gore@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m shaikh.mastan@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m aniket.ghube@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m vidushi.vashisth@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m shravani.deshmukh@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m meghana.raghuwanshi@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m sphoorty.sankppal@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m mona.chahal@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m raunak.tiwari@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m swati.patil@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m surbhi.saxena@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m priyanka.ujagare@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m vaidarbhee.hatwar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m prateek.arora@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m danish.mobin@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m anushka.wankar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ashutosh.bhambal@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m amruta.jewalikar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m raphayel.crasto@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m prithviraj.patil@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m sachin.chanvire@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m deven.shah@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m partha.das@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m william.correa@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m ashish.bisaria@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m mahesh.ginelu@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m purnendu.tripathy@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m jacklin.joseph@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m heena.jamadar@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m arun.nath@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m celine.tadke@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m harshal.chavan@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m sumeet.panchal@demandshore.com emptyFolder /
/opt/zimbra/bin/zmmailbox -z -m abhijeet.borade@demandshore.com emptyFolder /
/opt/zimbra/postfix/sbin/sendmail techsupport@demandshore.com < /tmp/mail.txt
